[project]
authors = ["Cali LaFollett <cali.lafollett@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community"]
description = "Add a short description here"
name = "life"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.6.0,<25"
python = ">=3.11,<3.13"
pygame = ">=2.6.1,<3"
